"use client";

import React from "react";
import Image from "next/image";
import styles from "./style.module.scss";

export default function LaserSkinRejuvenationContent() {
  return (
    <div className={styles.pageWrapper}>
      {/* Hero Section */}
      <section className={styles.heroSection}>
        <div className={styles.heroImageContainer}>
          <Image
            src="/img/assts/advanced-laser-facial/siama-photo-1.jpeg"
            alt="Laser Skin Rejuvenation Treatment"
            fill
            className={styles.heroImage}
            priority
            sizes="100vw"
            quality={95}
            style={{
              objectFit: "cover",
              objectPosition: "center",
            }}
          />
          <div className={styles.heroOverlay}>
            <div className={styles.heroContent}>
              <h1 className={styles.heroTitle}>Laser Skin Rejuvenation</h1>
              <p className={styles.heroSubtitle}>
                Advanced, non-surgical cosmetic procedure to restore youthful, healthy, and radiant skin
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className={styles.contentSection}>
        <div className={styles.container}>
          {/* Introduction */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Introduction</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation is an advanced, non-surgical cosmetic procedure designed to restore youthful, healthy, and radiant skin using state-of-the-art laser technology. It works by stimulating the skin&apos;s natural healing process, enhancing collagen production, and correcting multiple skin concerns at both surface and deeper levels. This treatment is widely preferred for individuals seeking visible skin improvement without surgery or prolonged downtime.
            </p>
            <p className={styles.paragraph}>
              With advancements in dermatological lasers, Laser Skin Rejuvenation has become one of the safest and most effective solutions for improving skin tone, texture, elasticity, and overall appearance—especially suitable for Indian and darker skin types when performed with the right technology.
            </p>
          </div>

          {/* What Is Laser Skin Rejuvenation */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>What Is Laser Skin Rejuvenation?</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation uses controlled laser energy to penetrate the skin layers and trigger cellular renewal. The laser energy gently heats the dermis (deep skin layer) while keeping the outer layer intact or minimally affected. This process stimulates fibroblast cells to produce new collagen and elastin—two essential proteins responsible for firm, smooth, and youthful skin.
            </p>
            <p className={styles.paragraph}>
              Depending on skin type and concern, dermatologists may use non-ablative, fractional, or hybrid laser systems to customize the treatment.
            </p>
          </div>

          {/* How It Works */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>How Laser Skin Rejuvenation Works</h2>
            <div className={styles.stepsList}>
              <div className={styles.stepItem}>
                <h3 className={styles.stepTitle}>Laser Energy Penetration:</h3>
                <p className={styles.stepDescription}>
                  The laser emits precise wavelengths that penetrate deep into the skin without damaging surrounding tissue.
                </p>
              </div>
              <div className={styles.stepItem}>
                <h3 className={styles.stepTitle}>Collagen Stimulation:</h3>
                <p className={styles.stepDescription}>
                  Heat generated by the laser activates collagen remodeling, encouraging the skin to repair itself naturally.
                </p>
              </div>
              <div className={styles.stepItem}>
                <h3 className={styles.stepTitle}>Cell Renewal:</h3>
                <p className={styles.stepDescription}>
                  Old, damaged skin cells are replaced with new, healthier cells, improving skin clarity and texture.
                </p>
              </div>
              <div className={styles.stepItem}>
                <h3 className={styles.stepTitle}>Gradual Improvement:</h3>
                <p className={styles.stepDescription}>
                  Results develop progressively over weeks as collagen production increases.
                </p>
              </div>
            </div>
          </div>

          {/* Skin Concerns Treated */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Skin Concerns Treated</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation is a multi-benefit treatment that addresses:
            </p>
            <ul className={styles.concernsList}>
              <li>Fine lines and early wrinkles</li>
              <li>Dull and tired-looking skin</li>
              <li>Uneven skin tone</li>
              <li>Mild pigmentation and sun damage</li>
              <li>Enlarged pores</li>
              <li>Rough skin texture</li>
              <li>Loss of skin elasticity</li>
              <li>Early signs of aging</li>
            </ul>
          </div>

          {/* Types of Laser Skin Rejuvenation */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Types of Laser Skin Rejuvenation</h2>
            <p className={styles.paragraph}>
              Depending on individual skin needs, dermatologists may recommend:
            </p>
            <div className={styles.typesGrid}>
              <div className={styles.typeCard}>
                <div className={styles.typeIcon}>🔹</div>
                <h3 className={styles.typeTitle}>Non-Ablative Laser Rejuvenation</h3>
                <ul className={styles.typeFeatures}>
                  <li>Targets deeper layers without removing skin</li>
                  <li>Minimal downtime</li>
                  <li>Ideal for mild aging and glow enhancement</li>
                </ul>
              </div>
              <div className={styles.typeCard}>
                <div className={styles.typeIcon}>🔹</div>
                <h3 className={styles.typeTitle}>Fractional Laser Rejuvenation</h3>
                <ul className={styles.typeFeatures}>
                  <li>Treats microscopic sections of skin</li>
                  <li>Effective for texture improvement and fine scars</li>
                  <li>Moderate downtime</li>
                </ul>
              </div>
              <div className={styles.typeCard}>
                <div className={styles.typeIcon}>🔹</div>
                <h3 className={styles.typeTitle}>Hybrid Laser Rejuvenation</h3>
                <ul className={styles.typeFeatures}>
                  <li>Combines ablative and non-ablative technology</li>
                  <li>Delivers faster and more visible results</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Benefits */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Benefits of Laser Skin Rejuvenation</h2>
            <ul className={styles.benefitsList}>
              <li>Improves overall skin texture and tone</li>
              <li>Restores natural glow and radiance</li>
              <li>Reduces fine lines and early wrinkles</li>
              <li>Boosts collagen and elastin production</li>
              <li>Minimally invasive and non-surgical</li>
              <li>Safe and effective for most skin types</li>
              <li>Long-lasting results with proper care</li>
            </ul>
          </div>

          {/* Ideal Candidates */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Ideal Candidates</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation is suitable for individuals who:
            </p>
            <ul className={styles.candidatesList}>
              <li>Have early signs of aging</li>
              <li>Want brighter, smoother skin</li>
              <li>Experience sun damage or dullness</li>
              <li>Have uneven skin texture or tone</li>
              <li>Prefer non-surgical skin treatments</li>
            </ul>
            <div className={styles.notRecommended}>
              <strong>❌ Not recommended for:</strong>
              <ul>
                <li>Active skin infections</li>
                <li>Pregnancy (depending on laser type)</li>
                <li>Certain medical skin conditions (to be evaluated by a dermatologist)</li>
              </ul>
            </div>
          </div>

          {/* Treatment Procedure */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Treatment Procedure</h2>
            <p className={styles.paragraph}>Step-by-Step Process:</p>
            <div className={styles.procedureSteps}>
              <div className={styles.procedureStep}>
                <div className={styles.stepNumber}>1</div>
                <div className={styles.stepContent}>
                  <h3 className={styles.stepTitle}>Consultation & Skin Assessment</h3>
                  <p>A detailed evaluation of skin type and concerns.</p>
                </div>
              </div>
              <div className={styles.procedureStep}>
                <div className={styles.stepNumber}>2</div>
                <div className={styles.stepContent}>
                  <h3 className={styles.stepTitle}>Skin Preparation</h3>
                  <p>Cleansing and application of protective gel or numbing cream if required.</p>
                </div>
              </div>
              <div className={styles.procedureStep}>
                <div className={styles.stepNumber}>3</div>
                <div className={styles.stepContent}>
                  <h3 className={styles.stepTitle}>Laser Application</h3>
                  <p>Controlled laser pulses are delivered across the treatment area.</p>
                </div>
              </div>
              <div className={styles.procedureStep}>
                <div className={styles.stepNumber}>4</div>
                <div className={styles.stepContent}>
                  <h3 className={styles.stepTitle}>Cooling & Protection</h3>
                  <p>Cooling techniques and soothing products are applied post-procedure.</p>
                </div>
              </div>
            </div>
            <div className={styles.procedureTime}>
              <strong>⏱ Procedure Time:</strong> 30–60 minutes
            </div>
          </div>

          {/* Pain & Comfort */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Pain & Comfort Level</h2>
            <ul className={styles.comfortList}>
              <li>Mild warmth or tingling sensation</li>
              <li>Most patients describe it as comfortable</li>
              <li>Numbing cream used if required</li>
            </ul>
          </div>

          {/* Recovery & Downtime */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Recovery & Downtime</h2>
            <ul className={styles.recoveryList}>
              <li>Mild redness for a few hours to 1 day</li>
              <li>Slight warmth or sensitivity</li>
              <li>No major peeling or scabbing (in non-ablative lasers)</li>
              <li>Patients can usually return to daily activities immediately.</li>
            </ul>
          </div>

          {/* Sessions Required */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Number of Sessions Required</h2>
            <ul className={styles.sessionsList}>
              <li><strong>Recommended:</strong> 3–6 sessions</li>
              <li><strong>Interval:</strong> 3–4 weeks apart</li>
              <li>Results improve gradually with each session</li>
            </ul>
          </div>

          {/* Results & Longevity */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Results & Longevity</h2>
            <ul className={styles.resultsList}>
              <li>Visible glow after first session</li>
              <li>Progressive improvement over 2–3 months</li>
              <li>Results can last 6–12 months or longer with maintenance and skincare</li>
            </ul>
          </div>

          {/* Pre & Post Treatment Care */}
          <div className={styles.careSection}>
            <div className={styles.careCard}>
              <h2 className={styles.careTitle}>Pre-Treatment Care</h2>
              <ul className={styles.careList}>
                <li>Avoid sun exposure for 7 days</li>
                <li>Stop active skincare ingredients (retinol, acids)</li>
                <li>Inform doctor about medications</li>
                <li>Keep skin clean and hydrated</li>
              </ul>
            </div>
            <div className={styles.careCard}>
              <h2 className={styles.careTitle}>Post-Treatment Care</h2>
              <ul className={styles.careList}>
                <li>Apply sunscreen regularly (SPF 30+)</li>
                <li>Avoid heat, sauna, and workouts for 24–48 hours</li>
                <li>Use gentle skincare products</li>
                <li>Avoid exfoliation for a few days</li>
              </ul>
            </div>
          </div>

          {/* Safety & Side Effects */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Safety & Side Effects</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation is FDA-approved and safe when performed by trained professionals.
            </p>
            <div className={styles.sideEffects}>
              <h3 className={styles.sideEffectsTitle}>Possible Temporary Effects:</h3>
              <ul className={styles.sideEffectsList}>
                <li>Redness</li>
                <li>Mild swelling</li>
                <li>Warm sensation</li>
              </ul>
              <p className={styles.sideEffectsNote}>
                Serious complications are rare.
              </p>
            </div>
          </div>

          {/* Comparison Table */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>
              Why Choose Laser Skin Rejuvenation Over Traditional Facials?
            </h2>
            <div className={styles.comparisonTable}>
              <div className={styles.tableHeader}>
                <div className={styles.tableCell}>Laser Skin Rejuvenation</div>
                <div className={styles.tableCell}>Traditional Facial</div>
              </div>
              <div className={styles.tableRow}>
                <div className={styles.tableCell}>Targets deep skin layers</div>
                <div className={styles.tableCell}>Works on surface only</div>
              </div>
              <div className={styles.tableRow}>
                <div className={styles.tableCell}>Boosts collagen</div>
                <div className={styles.tableCell}>No collagen stimulation</div>
              </div>
              <div className={styles.tableRow}>
                <div className={styles.tableCell}>Long-term results</div>
                <div className={styles.tableCell}>Short-term glow</div>
              </div>
              <div className={styles.tableRow}>
                <div className={styles.tableCell}>Medical-grade treatment</div>
                <div className={styles.tableCell}>Cosmetic treatment</div>
              </div>
            </div>
          </div>

          {/* Conclusion */}
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Conclusion</h2>
            <p className={styles.paragraph}>
              Laser Skin Rejuvenation is an advanced, science-backed solution for achieving youthful, radiant, and healthier skin without surgery. It addresses multiple skin concerns in a single treatment, making it ideal for individuals seeking visible results with minimal downtime. With customized laser settings and expert care, this treatment offers safe, effective, and long-lasting skin transformation.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

