import { getToken } from './admin';

// Use correct environment variables with fallback
const ADMIN_API_BASE_URL = process.env.NEXT_PUBLIC_ADMIN_API_BASE_URL || 'https://api.siama.in/api/v1/admin';
const PUBLIC_API_BASE_URL = process.env.NEXT_PUBLIC_PUBLIC_API_BASE_URL || 'https://api.siama.in/api/v1/public';

export interface ProductSession {
  _id: string;
  productId: string; // MongoDB ObjectId string
  sessionId: number;
  count: number;
  basePrice: number;
  discount: number;
  productName?: string; // Optional - populated by backend
  productSlug?: string; // Optional - populated by backend
  createdAt: string;
  updatedAt: string;
}

export interface PublicProductSession {
  productId: string; // MongoDB ObjectId string
  sessionId: number;
  count: number;
  price: string;
  finalPrice: string;
  discountPrice: string;
  discount: number;
  perSession: number;
}

export interface CreateProductSessionDto {
  productId: string; // MongoDB ObjectId string
  sessionId?: number; // Optional - will be auto-generated by backend
  count: number;
  basePrice: number;
  discount: number;
}

export interface UpdateProductSessionDto {
  count?: number;
  basePrice?: number;
  discount?: number;
}

interface ApiResponse<T> {
  success: boolean;
  message: string;
  data?: T;
  count?: number;
  total?: number;
  page?: number;
  pages?: number;
}

// Get All Sessions with Pagination
export async function getAllProductSessions(page: number = 1, limit: number = 10): Promise<ApiResponse<ProductSession[]>> {
  const token = getToken();
  if (!token) {
    throw new Error('No authentication token found');
  }

  const response = await fetch(`${ADMIN_API_BASE_URL}/product-sessions?page=${page}&limit=${limit}`, {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to fetch all product sessions' }));
    throw new Error(error.message || 'Failed to fetch all product sessions');
  }

  return response.json();
}

// Create Session Pricing
export async function createProductSession(data: CreateProductSessionDto): Promise<ApiResponse<ProductSession>> {
  const token = getToken();
  if (!token) {
    throw new Error('No authentication token found');
  }

  const response = await fetch(`${ADMIN_API_BASE_URL}/product-sessions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to create product session' }));
    throw new Error(error.message || 'Failed to create product session');
  }

  return response.json();
}

// Update Session Pricing
export async function updateProductSession(id: string, data: UpdateProductSessionDto): Promise<ApiResponse<ProductSession>> {
  const token = getToken();
  if (!token) {
    throw new Error('No authentication token found');
  }

  const response = await fetch(`${ADMIN_API_BASE_URL}/product-sessions/${id}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to update product session' }));
    throw new Error(error.message || 'Failed to update product session');
  }

  return response.json();
}

// Delete Session Pricing
export async function deleteProductSession(id: string): Promise<ApiResponse<null>> {
  const token = getToken();
  if (!token) {
    throw new Error('No authentication token found');
  }

  const response = await fetch(`${ADMIN_API_BASE_URL}/product-sessions/${id}`, {
    method: 'DELETE',
    headers: {
      'Authorization': `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to delete product session' }));
    throw new Error(error.message || 'Failed to delete product session');
  }

  return response.json();
}

// Get All Sessions for a Product
export async function getProductSessions(productId: string): Promise<ApiResponse<ProductSession[]>> {
  const token = getToken();
  if (!token) {
    throw new Error('No authentication token found');
  }

  const response = await fetch(`${ADMIN_API_BASE_URL}/product-sessions/${productId}`, {
    method: 'GET',
    headers: {
      'Authorization': `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to fetch product sessions' }));
    throw new Error(error.message || 'Failed to fetch product sessions');
  }

  return response.json();
}

// Get Public Session Pricing with Calculations (No Auth Required)
export async function getPublicProductSessions(productId: string): Promise<PublicProductSession[]> {
  const response = await fetch(`${PUBLIC_API_BASE_URL}/product-sessions/${productId}`, {
    method: 'GET',
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to fetch public product sessions' }));
    throw new Error(error.message || 'Failed to fetch public product sessions');
  }

  return response.json();
}
